### ISSUE TITLE
Misc. improvements to Circuit Builder

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#101]
- [x] - When a line is clicked, brighten its color so its distinguished from others
- [x] - When a cortical area is clicked, brighten the color of incoming and outgoing lines
- [ ] - Add a touchpad pan option
- [x] - Do not show the pop-up toolbar unless the mouse key is released. This will help it to be suppressed wifi user wants to drag and reposition. Also, do not show it on a long click
- [ ] - While dragging one or multiple cortical area, if the position hits the edges of the screen, pan the whole screen so room opens up for more dragging
- [ ] - Enable undo option when one or multiple nodes are moved

**Comment by Amir-Rasteg** [comment]
The remaining 3 suggestions should probably each be their own issue

**Comment by Amir-Rasteg** [comment]
> The remaining 3 suggestions should probably each be their own issue

done, since the other suggestions here were implemented, closing this github issue
