### ISSUE TITLE
Crashed after created OPU

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#108]
branches:
FEAGI: structured-errors
BV: standardized_web_error_handling

Last seen on BV:
![image](https://github.com/feagi/brain-visualizer/assets/65916520/90b80d8d-7c6b-4332-b07b-8334b362126a)

BV error:
![image](https://github.com/feagi/brain-visualizer/assets/65916520/7226307d-04ff-46df-b206-344206de64b4)

Steps:
1) Load bare bones
2) Create a custom cortical area
3) Error displaying

**Comment by Amir-Rasteg** [comment]
resolved
