### ISSUE TITLE
menu diagloue reset to the position

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#109]
It will reset the position every time it reached to the "end" of the screen. 

branches:
FEAGI: structured-errors
BV: standardized_web_error_handling

https://github.com/feagi/brain-visualizer/assets/65916520/b1542ce3-f570-4fe8-8b5d-f3b4412fc3f9

**Comment by Amir-Rasteg** [comment]
This is intentional behavior to keep the user from dragging he window out of bounds. However it needs some tweaking

**Comment by Amir-Rasteg** [comment]
resolved with some tweaks to make the mapping editor window smaller
