### ISSUE TITLE
Crash when update the morphology on vector

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#111]
branches:
FEAGI: structured-errors
BV: standardized_web_error_handling

![image](https://github.com/feagi/brain-visualizer/assets/65916520/b704bc7f-64f5-42ae-9104-303fca3e7876)

Last seen:
![image](https://github.com/feagi/brain-visualizer/assets/65916520/c0c7d039-a55f-4747-a03d-041bed22a98a)

Steps:
1) Click moprhology rules
2) Click any with vector
3) Click update
4) Error

**Comment by Amir-Rasteg** [comment]
resolved
