### ISSUE TITLE
Crash after edit something new on morphology

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#147]
1) Create a new morph or select an existing morp
2) Add new row (Vector and Patterns either way)
3) Edit whatever
4) Add 
5) Crashed
![image](https://github.com/feagi/brain-visualizer/assets/65916520/be19a336-e825-477b-a19a-84ab6a215534)

See the video

https://github.com/feagi/brain-visualizer/assets/65916520/66e68733-0c23-48e4-8326-32d9999be750

**Comment by Amir-Rasteg** [comment]
![image](https://github.com/feagi/brain-visualizer/assets/127231771/c883318b-391d-4544-8b8e-27f714ca76f3)
Seems that FEAGI will (sometimes?) not send the class of a morphology, which is where the error is stemming from @m-nadji-tehrani

**Comment by Amir-Rasteg** [comment]
fixed
