### ISSUE TITLE
BV crashed when synpantic or membrane is on locally

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#149]
![image](https://github.com/feagi/brain-visualizer/assets/65916520/a898d88d-d514-47f9-b065-cc159b135e3e)

1) Just to make sure one of them is toggled on
2) Open that cortical that has it toggled on
3) See the error

**Comment by Amir-Rasteg** [comment]
I cannot repo this?

**Comment by Kakcalu13** [comment]
No longer issue, fixed
