### ISSUE TITLE
Split View dropdown exhibits inconsistent behavior upon different selections

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#164]
In some cases the dropdown shows the selected view as enabled on the top spot. In some cases it doesn't.

<img width="112" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/3f6b5d95-dede-41af-83f9-48878ca6aad0">
<img width="195" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/3b97592d-422b-4a5e-8b8f-67eda013a4cf">

**Comment by Amir-Rasteg** [comment]
behavior changed
