### ISSUE TITLE
Missing Tooltips

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#165]
- Do a full audit of UI elements and add missing tooltips.

**Comment by Amir-Rasteg** [comment]
did a pass on top bar which was missing a lot. Without being able to run feagi currently I cannot check too much else, let me know if any other tooltips are missing

Due to the odds theres probably some I missed, keeping this issue open

**Comment by Amir-Rasteg** [comment]
Note: Mapping editor is likely missing tooltips
