### ISSUE TITLE
Click any button on the topbar doesn't launch a new dialogue

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#170]
https://github.com/feagi/brain-visualizer/assets/65916520/e577712c-48a7-448c-9760-2c6d418d4f7e

**Comment by Kakcalu13** [comment]
HZ, creating ipu, opu and memory, decrease/increase size of topbar are not working

**Comment by Amir-Rasteg** [comment]
fixed HZ, decrease/decrease needs conversations. The other issues arent relevant to this issue and are covered in https://github.com/feagi/brain-visualizer/issues/175

**Comment by Kakcalu13** [comment]
https://github.com/feagi/brain-visualizer/assets/65916520/62ff3058-5034-46a5-9db3-cc4d8df9eef3

hz is still using old hz even if updated

**Comment by Kakcalu13** [comment]
fixed confirmed

**Comment by Kakcalu13** [comment]
hz is fixed but there are other things

**Comment by Kakcalu13** [comment]
creating a new issue for size buttons
