### ISSUE TITLE
Continuing mapping to another cortical after created two different corticals

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#184]
1) Add motion control
2) QC itself with projector
3) Add misc
4) Increase Misc's dimension to 4x1x1
5) Activate motion control once
6) Activate anything on MISC and it will qc projector on motion control itself.

 

https://github.com/feagi/brain-visualizer/assets/65916520/28545c52-c2bc-45dc-adef-c1fcac6cfff5

Before relaunch BV:
![image](https://github.com/feagi/brain-visualizer/assets/65916520/11a7bd45-dcbc-4676-970a-fbd6371e670e)

After relaunch BV:
![image](https://github.com/feagi/brain-visualizer/assets/65916520/aebc15db-36ec-445b-81f0-3eade98b9635)

**Comment by Kakcalu13** [comment]
Seems like this is FEAGI issue. It occurs on OPU only, not custom

**Comment by Kakcalu13** [comment]
I'm able to repo this easier:
1) Load Barebones (easiest genome)
2) Add Any OPU
3) Add another OPU
4) Check CB and see no map.
5) Reload BV and open the CB again, see that they are mapped

**Comment by Kakcalu13** [comment]
still able to repo this easily especially using API:

1) Load essential
2) Create OPU of servo
3) Create IPU of IR
4) Load it
5) See that IR mapped to Servo OPU automatically



Using API only:
endpoint: /v1/cortical_area/cortical_area


1) 
```
{
  "cortical_type": "OPU",
  "cortical_id": "o__ser",
  "coordinates_2d": [
    0,0
  ],
  "coordinates_3d": [
    40,0,0
  ],
  "channel_count": 1
}
```

2) 
```
{
  "cortical_type": "IPU",
  "cortical_id": "i__inf",
  "coordinates_2d": [
    0,0
  ],
  "coordinates_3d": [
    70,0,0
  ],
  "channel_count": 1
}
```
reload BV and see the issue

**Comment by Kakcalu13** [comment]
After restart everything and start FEAGI only.

Here is what I did:
1) Load essential genome thru api
2) Add Servo OPU thru API
3) Add IR thru API
4) Save genome
5) Load the saved genome
6) It is no longer there

I afraid something trigger that and we overlooked that

**Comment by Amir-Rasteg** [comment]
@Kakcalu13 any update on this?

**Comment by Amir-Rasteg** [comment]
@Kakcalu13 Was this ever fixed?

**Comment by Kakcalu13** [comment]
This is confirmed on feagi side

**Comment by Amir-Rasteg** [comment]
seems to be long fixed feagis side
