### ISSUE TITLE
Sends vector when update patterns in BV

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#185]
```
**2024-04-14 12:07:51,170:INFO:api.api:log_requests:88:rid=9A0EWB start request path=/v1/morphology/morphology
**************************************************
 {'update_morphology_properties': {'name': 'test_morph', 'type': 'vectors', 'class': 'custom', 'parameters': {'patterns': [[[0, 0, 0], [25, 0, 0]]]}}}
2024-04-14 12:07:51,172:INFO:api.api:log_requests:95:rid=9A0EWB completed_in=1.90ms status_code=200
INFO:     127.0.0.1:52051 - "PUT /v1/morphology/morphology HTTP/1.1" 200 OK
<><><><><>   <><><><> Impacted areas [['C8Gtes', 'o__ser']]
C8Gtes o__ser
++++++ 3
Error during synaptogenesis of C8Gtes and o__ser
Traceback (most recent call last):
  File "/Users/bwuk/feagi/src/../src/evo/synaptogenesis_rules.py", line 96, in neighbor_finder
    for vector in runtime_data.genome["neuron_morphologies"][neuron_morphology]["parameters"]["vectors"]:
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'vectors'

genome is saved**
```

Repo using barebones:

1) Add servo opu (2x0x10
2) Add custom cortical (name whatever u want)
3) Create a new morph using patterns. 0-0-0 to 0-0-0
4) Map custom cortical to servo opu on the new morph
5) go to the new morph you created, add new rule 0-0-0 to 1-0-0
See the error on FEAGI

**Comment by Kakcalu13** [comment]
Confirmed that this is on genome-physiology and independent_core

**Comment by Amir-Rasteg** [comment]
the dictionary sent was this:

 {'update_morphology_properties': {'name': 'dddddddd', 'type': 'vectors', 'class': 'custom', 'parameters': {'patterns': [[[0, 0, 0], [0, 0, 0]], [[0, 0, 0], [1, 0, 0]]]}}}

Seems to have the patterns parameter to me. this is also visible in your example.

@m-nadji-tehrani this may be a feagi side issue? The error suggest feagi is searching for a "vectors" parameter

**Comment by Amir-Rasteg** [comment]
> vectors

not sure how I missed the vectors in the middle

Pushed fix now BV side

**Comment by Kakcalu13** [comment]
confirmed fixed
