### ISSUE TITLE
Update cortical area blocks green voxel until hard reset

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#186]
https://github.com/feagi/brain-visualizer/assets/65916520/1c94701f-3dbb-4245-8110-92c7f7a98250

**Comment by Amir-Rasteg** [comment]
Reclassifying the issue following testing:

The green voxels do not persist if the cortical properties window is open, regardless if any changes are made or not. closing the window mitigates the problem.

Investigating...

**Comment by Kakcalu13** [comment]
confirmed its fixed
