### ISSUE TITLE
Unable to update anything after reload genome 

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#190]
![image](https://github.com/feagi/brain-visualizer/assets/65916520/ee8d1b92-d405-49f2-95c0-cd8fa6390314)

I clicked delete button and it doesn't work

**Comment by Kakcalu13** [comment]
https://github.com/feagi/brain-visualizer/assets/65916520/0dd3a04e-8885-4e43-9c90-e4377d5ff6dd

Apparently, this occurs when you reload genome and everyhting on API is not working properly anymore until you relaunch

**Comment by Amir-Rasteg** [comment]
I can no longer repo this with the new genome changes

**Comment by Kakcalu13** [comment]
confirmed the fix
