### ISSUE TITLE
New connections made in CB should default to Projector

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#215]
When a new connection is made using CB, the default mapping is not showing up. Projector should be the default for non-memory and "memory" should be the default when connecting to memory type cortical area

<img width="696" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/3b1a44e7-4a47-44e7-8ea1-00f1aba9df28">

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani I cant repo this, when I connect to cortical areas, the defaults are correct as listed above

**Comment by Amir-Rasteg** [comment]
closed as per discussion, reopen if a repo is found
