### ISSUE TITLE
Shadow boxes behave inconsistently when adjusting the size of cortical area

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#216]
Refer to the attached image. increased the height of the cortical area and reduced it to 1 but the height of the shadow box remained large

<img width="828" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/5ac4c678-afa1-4844-8453-7f2642ceed8f">

and it can become pretty distorted when changing values
<img width="366" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/cceda224-262a-4a46-a023-0e3a52a84762">

**Comment by Amir-Rasteg** [comment]
this is fixed
