### ISSUE TITLE
Introduciton of Brain Regions

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#219]
**Definition**
Brain regions are grouping of one or multiple cortical areas which can provide many benefits including:
- help better organizing brain structures in functional units
- reduces clutter
- makes sharing easier
- provides building blocks that can be assembled together

**Properties**
- By default, the entire genome is considered a single brain region
- brain regions can be nested and each brain region can contain one or more other brain regions or cortical areas or a combination of both
- Each brain region will have a unique id within the genome
- Each cortical region will have a text label
- Each brain region will have a 2D and 3D coordinate that would help identify it within the 3D Brain Monitor and Circuit Builder
- All 2D and 3D locations are local coordinates in perspective to the parent region.
- The size of each brain region will be dependent on the coordinates of its children

**Behaviors**
Identification:
- Top bar should have a new option for brain regions that would be similar to existing cortical areas list feature. 
- All brain regions should be listed with the ability to filter by name
- Selecting a given brain region should open a new tab with the brain region content within
- Similar to cortical areas, there should be an add button to create a new region

Creation dialogue:
- A new Create Brain Region dialogue is needed to facilitate the creation of brain region.
- Brain region creation process should include:
        - Title (required)
        - 3D coordinate (required)
        - Members (required) [user should be able to view a list of existing brain regions and cortical areas and select from the list
        - if there is an existing incomming mapping toward any of the brain region members, that cortical area will be automatically labled as a local IPU
        - if there is an existing mapping that is outgoign from a cortical part of a brain region to a cortical area outside the region then such cortical area will be designated as a local OPU
     
Deletion:
        - cortical regions will be automatically deleted if the last member within is deleted. A deletion which would lead to the deletion of a parent brain region should result in a warning and solicit confirmation from the user
        - [P2] a region can be manually deleted:
             1. soft delete: will result in disassociation of all members and re-association of members with the parent region
             2. hard delete: will result in deletion of all its members from genome (Destructive but helpful when a large import needs to be reversed)

Modification:
        - With the exception of the brain region id, all other properties should be user editable
        - User should be able to drag the title bar of a brain region in CB to change its 2D position
        - pop-up toolbox in 3D monitor should include an option to change position. The button should pop-up a vector box that enables user to change its 3D location similarly for cortical areas. 
        - if a cortical area is deleted it will be automatically removed from the brain region registry
        - a new pop-up toolbox button should be added to enable user change the association of a cortical area from one brain region to another by simply selecting a destination brain region from a list

Restrictions:
       - region of type "root" is the default that covers the entire genome and cannot be deleted
       - cortical areas of type CORE, IPU, and OPU can only be a member of the root brain region

Other considerations
       - Genome augmentation aka. amalgamation will import cortical areas and brain regions both
       - 
       

**API**
<img width="647" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/5d6eeca8-426b-4c74-98e4-bfdb2683232f">

FEAGI region registry sample:

`
{
  "brain_regions": {
      "b_412414124": {
        "title": "visual pathway",
        "type": "root",
        "members": {
          "___pwr": {
            "type": "area",
            "coordinate_2d": [3, 12],
            "coordinate_3d": [3, 12, 33]
          },
          "_death": {
            "type": "area",
            "coordinate_2d": [0, 0],
            "coordinate_3d": [1, 1, 1]
          },
          "b_252342343243": {
            "type": "region",
            "coordinate_2d": [0, 0],
            "coordinate_3d": [1, 1, 1]
          }
        }
      },
      "b_4234234234": {
        "title": "motor pathway",
        "type": "child",
        "members": {
          "VFWEDF": {
            "type": "area",
            "coordinate_2d": [3, 12],
            "coordinate_3d": [3, 12, 33]
          },
          "VFWED2": {
            "type": "area",
            "coordinate_2d": [0, 0],
            "coordinate_3d": [1, 1, 1]
          },
          "b_252342343245": {
            "type": "region",
            "coordinate_2d": [0, 0],
            "coordinate_3d": [1, 1, 1]
          }
        }
      }
  }
}
`

**Comment by Amir-Rasteg** [comment]
looks like a good starting point. Also suggest a function to remove cortical areas from a region

**Comment by Amir-Rasteg** [comment]
Commenting further discussion
- Regions should support "hints" / "suggested" mappings when connecting an input and output
- I personally strongly suggest allowing user defined labels for these inputs and outputs
- These suggested mappings are part of the region object, not the connectome. They only get added to the connectome when a user makes a connection
- Note -> beware of issues of hints when user connects a region output to an input

**Comment by Amir-Rasteg** [comment]
(instead of making separate issues, will post here)

v1/region/regions is currently unimplemented
v1/region/region is a get request with a body

Currently the input / output structure looks like this:
![image](https://github.com/feagi/brain-visualizer/assets/127231771/c5abdc5f-793e-498e-84a8-0a6086ddbcd9)
Instead, we should have an array per cortical area with the full mapping details

**Comment by Amir-Rasteg** [comment]
The input / output structure I suggest can look something like this

`
{
  "inputs": {
    "iv00_C": {
      "name": "String_Goes_Here",
      "mappings": {
        [
          {"morphology_id": "projector",
            "morphology_scalar": [
              1,
              1,
              1
            ],
            "postSynapticCurrent_multiplier": 1,
            "plasticity_flag": false,
            "plasticity_constant": 1,
            "ltp_multiplier": 1,
            "ltd_multiplier": 1
          },
        ]
      }
    }
  }
}
`

(where mappings is an array of mappings using the same structure seen elsewhere in feagi)

**Comment by Amir-Rasteg** [comment]
current summary call is missing dimension information

**Comment by Amir-Rasteg** [comment]
summary of missing data points I am running into currently:
- No dimension information in summary endpoint
- No Suggested mappings for inputs or outputs

**Comment by Amir-Rasteg** [comment]
Critical bug: Not all regions contain a 3d coordinate, only the root

**Comment by Amir-Rasteg** [comment]
> name

change the dict to a list, include the name value within the list dictionary element

**Comment by Amir-Rasteg** [comment]
more detail for above:

inputs / outputs should not contain IPUs/OPUs
ignore the previous suggestion about splitting input/outputs for cortical areas and regions, I can calculate regions locally
inputs / outputs should be a flat array with each element being a dictionary with a name property, and a mapping(s) property

**Comment by m-nadji-tehrani** [comment]
> Critical bug: Not all regions contain a 3d coordinate, only the root

Fixed

**Comment by Amir-Rasteg** [comment]
implemented
