### ISSUE TITLE
Max neuron limits are not properly handled

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#223]
- FEAGI returns a 400 error when exceeding threshold. that should be passed on to user which is not happening at this time

**Comment by Amir-Rasteg** [comment]
is able to repo currently:
- set neuron limit to 14k (slightly below default genome)
- create a 10x10x1 cortical area to get right under the limit
- set the neuron density to 2. This goes over the limit and feagi returns a 400. BV logs the error but does not inform the user
