### ISSUE TITLE
Misleading error when creating cortical areas with one letter

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#224]
Even though there are no cortical areas with the name 'h', the error message is indicating that user cannot create it due to name conflict.

<img width="609" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/5d1e7407-5fbe-4a61-a11a-4c0c3d6e974a">

**Comment by Amir-Rasteg** [comment]
fix was just pushed for the window being too aggressive
