### ISSUE TITLE
Doesn't save region

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#226]
https://github.com/feagi/brain-visualizer/assets/65916520/c2014afa-6973-498c-a6c7-dbbe2f4e6850

lost all progress after reload bv

**Comment by Amir-Rasteg** [comment]
can you try this again but not using the core area brain power?

**Comment by Amir-Rasteg** [comment]
confirmed this end this only occurs if you attempt to put in a core / ipu / opu area in FEAGI, feagi will prevent the creation of the region at all

**Comment by Amir-Rasteg** [comment]
placing core / ipu / opu is now blocked BV side, we still need it to be bloked feagi side @m-nadji-tehrani
