### ISSUE TITLE
Cannot modify plasticity constant and LTP/LTD multiplier for memory area efferent

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#230]
When a memory connection is projected to another cortical area, plasticity can be enabled but plasticity parameters are not.

<img width="853" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/3117a286-75db-4875-85ff-41a37be1dcba">

**Comment by Amir-Rasteg** [comment]
this seems to be fixed with the rebuild of the mapping window
