### ISSUE TITLE
Misc bugs on Brain Regions

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#232]
1. Only have the cortical area name and remove “selected area”
<img width="273" alt="Selected Area asdf" src="https://github.com/feagi/brain-visualizer/assets/26581495/6873d562-5d93-4d8f-9f7d-dd7dfc4643ec">

￼

2. Bring back the dragging behavior of prior CB where when user drags the area/region, the pop up menu is not displayed
3. Exception when clicking on the cortical in 3D monitor
<img width="585" alt="Pasted Graphic 113" src="https://github.com/feagi/brain-visualizer/assets/26581495/b0360c36-659e-42d4-9288-b7fd2bc43c0d">

4. After creating a new custom cortical area it did not show up on CB
5. Cortical area 2D positions are being reset
6. Add a new OPU and connect an existing custom area to it, mapping does not show up unless Godot is restarted
7. Rename tooltip to “Add to brain region” then open region explorer let the user choose and existing region which will be majority of the case. At the bottom of the explorer add a button labeled “New Region” which would then open create new region. 
<img width="294" alt="Add to a new region" src="https://github.com/feagi/brain-visualizer/assets/26581495/b69630b7-a65a-48af-9bca-326240ba228b">

**Comment by Amir-Rasteg** [comment]
These all seem to be fixed
