### ISSUE TITLE
Reload issue

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#234]
When it reload, it display two of genome overlays. If any cortical area is being clicked, it will crash bv. See here:

https://github.com/feagi/brain-visualizer/assets/65916520/3e6a3e59-4e57-43c4-ad3a-a4666beb5f4a

**Comment by Kakcalu13** [comment]
![image](https://github.com/feagi/brain-visualizer/assets/65916520/da4914d2-0425-404f-baf0-b5eeee0e9bfa)

Error here

**Comment by Kakcalu13** [comment]
persists

**Comment by Kakcalu13** [comment]
persists :(

**Comment by Kakcalu13** [comment]
persists on June 14 2024 🗣️ 🗣️

**Comment by Amir-Rasteg** [comment]
this should be resolved, however leaving open until further confirmed since I can only test with amalgamation
