### ISSUE TITLE
When the left bar opened, it doesn't updated itself every click on a different cortical area

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#235]
Previously, BV shows the different cortical area on left bar whenever the cortical is being clicked

https://github.com/feagi/brain-visualizer/assets/65916520/7ea40707-e938-4ef7-bead-33c21b9e3dfd

**Comment by Kakcalu13** [comment]
persists on June 14 2024

**Comment by Amir-Rasteg** [comment]
fixed

**Comment by Kakcalu13** [comment]
its back

**Comment by Amir-Rasteg** [comment]
added back to new multiwindow
