### ISSUE TITLE
QC crashed

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#244]
![image](https://github.com/feagi/brain-visualizer/assets/65916520/98628af2-393f-4160-87bd-d0860f11154e)

a picture before crash Godot
![image](https://github.com/feagi/brain-visualizer/assets/65916520/cac61ee7-fa9e-47e4-a587-f8438d6ae2f1)

**Comment by Amir-Rasteg** [comment]
this should be resolved
