### ISSUE TITLE
Error while making a copy of a custom cortical area in CB

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#250]
- Create a custom cortical area.
- click on it using CB or BM
- select make a copy using the pop-up tool bar

<img width="554" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/d03c90cf-5217-42be-b787-61268e1c51c1">

**Comment by Amir-Rasteg** [comment]
fixed
