### ISSUE TITLE
Misc. add to region enhancements

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#252]
When adding a cortical area to a region:

- rename the window title to "Select a Target Brain Region"
- in the case there is no subregion available, directly launch create new region window
- rename "add region" button to "Create Brain Region"
<img width="361" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/d7eb56ac-a453-4f17-a903-320817d9d16e">

- When displaying the candidates to user for adding to a region, do not show the ones already added 
- Enable user to select multiple areas at the same time when adding. (need to address multi select holistically)
- rename "Select object from genome" to "Select Candidates"
<img width="353" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/9b140ec9-8744-48d0-90b6-e1a7198cc0ad">

**Comment by Amir-Rasteg** [comment]
Current redesign handles added these improvements
