### ISSUE TITLE
Region/Area picker window should filter content based on context

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#256]
In the following example I dragged the output of the brain region on left and connected it to the cortical area on right. The mapping window popped up with source as empty and destination as cortical area. When clicking on the source, I am presenting with all possible regions and areas. the picker window should start from the root of brain region that the mapping was initiated.

<img width="1197" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/b3841b10-78f3-4b39-bd76-d326481e212b">

**Comment by Amir-Rasteg** [comment]
Complete
