### ISSUE TITLE
Implement a loading indicator

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#258]
When long running operations are in play, FEAGI will set a flag in health check. BV should prompt the user that an operation is in progress and they need to wait. During such operation all UI controls should be locked and used should not be able to initiate any operation leading to an API call other than health check that happens automatically.

brain_readiness key in health check can be used for this purpose. Anytime it's false, display the indicator that brain operation is in progress, please wait.

**Comment by Amir-Rasteg** [comment]
we have a basic loading indicator in place, but it could use more work
