### ISSUE TITLE
self connect doesn't display in BV

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#260]
![image](https://github.com/feagi/brain-visualizer/assets/65916520/7a4d507c-7ba2-45aa-ab55-826bcfca6d97)

This is without self connection.

Now I add the self connection
![image](https://github.com/feagi/brain-visualizer/assets/65916520/e3abc3a1-d03f-42ad-a61d-ed53a1e792a7)

I can't open any information or connections off self connected
![image](https://github.com/feagi/brain-visualizer/assets/65916520/dd8709a1-3fc2-44a7-8a22-724b10fcba1e)

**Comment by Amir-Rasteg** [comment]
long addressed
