### ISSUE TITLE
import regions-->IPU/OPUs

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#263]
after importing the regions, the IPU/OPUs are all being placed at 0,0,0

**Comment by Kakcalu13** [comment]
since this issue is already created, this happens to me too

![image](https://github.com/feagi/brain-visualizer/assets/65916520/f70832a2-3054-4f4b-a4e1-5023339344e5)

**Comment by Kakcalu13** [comment]
After reviewing the process, I find that FEAGI returns 0,0,0. It's not BV issue. This is FEAGI issue

![image](https://github.com/feagi/brain-visualizer/assets/65916520/b1e1b13e-9ca0-46ed-ab1e-8f192b5732c1)


@m-nadji-tehrani FYI

**Comment by Kakcalu13** [comment]
1) Import
2) Use the api: cortical_area_geometry_v1_cortical_area_cortical_area_geometry_get
3) See IPU set to 0,0,0

**Comment by Amir-Rasteg** [comment]
long fixed
