### ISSUE TITLE
Review criteria for "connection to FEAGI lost" message

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#269]
When there is loss of API connectivity with FEAGI, the "Connection to FEAGI lost" message is displayed but seems like it gives up immediately. We need better handling so proper retry count with proper retry frequency is set for recovery.

- Define a configurable retry count and keep it in a global config file
- Define a rety frequency
-

**Comment by Amir-Rasteg** [comment]
we added  basic retry a while back
