### ISSUE TITLE
Mapping lines from a region visually look off until a region is clicked

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#273]
After region R2 was created on the Essential genome, the lines are initially mis-aligned until clicking on one of the regions.

<img width="784" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/f53de272-4efb-43e6-a5f0-848303c4d1f5">

**Comment by Amir-Rasteg** [comment]
partial fix pushed, proper fix later

**Comment by Amir-Rasteg** [comment]
appears fixed, reopen if a repo is found to cause this again
