### ISSUE TITLE
Amalgamation that includes suggested input/output leading to exception

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#274]
- Amalgamate the attached genome to Essential genome
- Godot exception below is observed

<img width="1125" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/5480401b-4f52-4de3-b567-e48442d0f9cf">
[memory.json](https://github.com/user-attachments/files/16113719/memory.json)

**Comment by Amir-Rasteg** [comment]
Seems to be related to https://github.com/feagi/brain-visualizer/issues/268

**Comment by Amir-Rasteg** [comment]
a fix for this has been pushed bv side to catch when feagi sends invalid data, however feagi needs to be fixed to prevent this from happening
