### ISSUE TITLE
IPU/OPU connections to the region are being imported as afferent as opposed to efferent (IMPORTANT)

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#275]
as title

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani in my testing, this seems to be a FEAGI issue, as I am seeing in various endpoints (IE v1/cortical_mapping/cortical_map) that mappings from [source are in region] to [destination area outside region] end up being returned at this endpoints in the opposite direction

**Comment by m-nadji-tehrani** [comment]
Fixed on local branch.
