### ISSUE TITLE
Camera move to chosen cortical area is broken

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#278]
When selecting a cortical area from the cortical list, the camera should move unclose to that area. This feature is broken since the introduction of cortical area activity view checkboxes.

<img width="153" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/aa4c8821-fe26-4516-8eab-1b088b831d50">

**Comment by Amir-Rasteg** [comment]
readded
