### ISSUE TITLE
Cortical areas move around circuit builder

### ISSUE THREAD

**Issue by KatherineFronczak** [feagi/brain-visualizer#279]
after reloading or restarting an experiment, cortical areas will move to a different place in circuit builder. Connections are maintained, just the physical position on the grid changes. Not a huge issue, just makes it a little difficult when have an organized complex circuit.

**Comment by Amir-Rasteg** [comment]
I need some repo steps for this as I cannot repo this

**Comment by Amir-Rasteg** [comment]
closing this issue as we have several like this, and it is almost always a result of feagi sending incorrect information
