### ISSUE TITLE
**URGENT**create cortical mapping

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#28]
creating a second mapping overrides the first mapping

**Comment by jenz512** [comment]
pick SR_latch_NOR from logic_gates folder (this is a OLD genome)
create a mapping
create a second mapping
you will see creating the second one overrides the first one

**Comment by Amir-Rasteg** [comment]
I cannot repo this

**Comment by Amir-Rasteg** [comment]
this has been resolved a while ago
