### ISSUE TITLE
When update properties, it doesn’t let me update

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#285]
https://github.com/user-attachments/assets/9ce82adc-d4d0-4d1e-bc2e-432e2e464f2f

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani FEAGI is still returning HTTP 500 when using multi edit

**Comment by Kakcalu13** [comment]
that has nothing to do with the issue.

I'm talking about the button that does not lit up whenever I change the value

**Comment by Kakcalu13** [comment]
I re-updated video

**Comment by Amir-Rasteg** [comment]
should be working now

**Comment by Amir-Rasteg** [comment]
moving the 500 issue to its own issue here https://github.com/feagi/feagi/issues/480
