### ISSUE TITLE
pattern mappings are showing all zeros

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#287]
as title

**Comment by jenz512** [comment]
with the new built

**Comment by Amir-Rasteg** [comment]
I cannot repo this?
![image](https://github.com/user-attachments/assets/eb758fe2-982f-4ff2-aeb7-20adcfcbc837)

**Comment by Kakcalu13** [comment]
I'm able to verify this on my end.

![image](https://github.com/user-attachments/assets/d8cee542-eb95-4834-b6be-eab7d8d32fd0)


![image](https://github.com/user-attachments/assets/22baaa4b-15aa-4981-9248-93531be95567)

**Comment by Amir-Rasteg** [comment]
fixed
