### ISSUE TITLE
leftbar displays all zeroes

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#302]
![image](https://github.com/user-attachments/assets/a52601b3-0244-418d-8947-66b7fc6fe6e4)

**Comment by Amir-Rasteg** [comment]
How can this be repo'd?

**Comment by Kakcalu13** [comment]
![image](https://github.com/user-attachments/assets/f32c8569-9ab3-474b-a75d-c46413ce086a)


1) Load gneome
2) click any cortical
3) See the leftbar (after u enable advance mode)

**Comment by Amir-Rasteg** [comment]
![image](https://github.com/user-attachments/assets/16fd6e76-e7d5-468e-a72e-444d872344d3)
cant repo this.

send me the genome you are using please

**Comment by Kakcalu13** [comment]
closing since feagi needs to be updated
