### ISSUE TITLE
Changing FEAGI refresh rate is very clunky 

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#304]
When changing the FEAGI refresh rate from the top menu bar, sometimes the value doesn't update. Sometimes extra zero comes in. please test it thoroughly and use click away and enter both for changing the value.

**Comment by Amir-Rasteg** [comment]
Seems fine to me? Cannot replicate any odd behavior.

If it does keep occurring, please let me know what platform, and what specifically (IE keypresses) you are doing and what you expect to happen
