### ISSUE TITLE
BV settings is visually incomplete

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#312]
The UI is not looking professional. Please make the following adjustments:
- the right side of version and ui magnification to be flushed with other UI elements such as toggles
- camera animation text to be flushed left with other items
- use similar theming as the cortical properties for the camera settings so the title bar is slightly different color consistent with cortical properties

<img width="493" alt="image" src="https://github.com/user-attachments/assets/fd94329e-a9c0-45bd-b3d0-84bcf16b5be1">

**Comment by Amir-Rasteg** [comment]
long fixed
