### ISSUE TITLE
When "MP driven PSP" is on, gray out "Post synaptic potential (PSP)"

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#314]
MP driven PSP overwrites the effect of the "post synaptic potential (PSP)" field. It will be misleading to have PSP value editable with MP drive PSP is on. 

When MP driven PSP is on:
1. gray out the PSP field
2. change its value to N.A.
3. Add a tooltip as "MP driven PSP supersedes the PSP setting"

Ensure when mp driven psp is turned off everything reverts back.

NOTE: By mistake, PSP Uniformity is graying out the PSP field at this time.

<img width="183" alt="image" src="https://github.com/user-attachments/assets/d39dcd44-a41c-442b-afa5-1624edef91e9">

**Comment by Amir-Rasteg** [comment]
added in PR https://github.com/feagi/brain-visualizer/pull/310
