### ISSUE TITLE
can't change PSP unless you turn MP driven on and back off again

### ISSUE THREAD

**Issue by KatherineFronczak** [feagi/brain-visualizer#329]
On Monday jul 29th, I had to turn off PSP uniformity to edit PSP. However today, that does not work anymore. I now have to turn MP driven PSP on and then back off again to be able to edit PSP. I have to do this every time I want to edit the PSP.

**Comment by m-nadji-tehrani** [comment]
This is a very important parameter blocking progress. when fixing it, please ensure the fix is properly tested and ensure nothing around it is being broken. We have been running into so many issues in this area and they could have been prevented.

**Comment by m-nadji-tehrani** [comment]
When BV is first opened, PSP field is grayed out under the cortical properties window.

Only when MP driven PSP is on the PSP field should be grayed out and the value inside should show as NA 

<img width="180" alt="image" src="https://github.com/user-attachments/assets/a28ce74d-1d6a-4eef-ab8f-60cccd5e33d1">
