### ISSUE TITLE
Missing features: Magnification, create IO, visualization skip rate, visualization suppression threshold

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#332]
I couldn't find it in https://github.com/feagi/brain-visualizer/blob/staging/godot_source/Utils/JavaScriptIntegrations.gd

**Comment by Amir-Rasteg** [comment]
added
![image](https://github.com/user-attachments/assets/3da3eec5-30de-4404-bc2b-8801eeb656d8)
