### ISSUE TITLE
mapping selection scroll isn't working

### ISSUE THREAD

**Issue by KatherineFronczak** [feagi/brain-visualizer#340]
when establish connection between two cortical areas and use scroll menu to define mapping, the scroll doesn't work.

**Comment by Amir-Rasteg** [comment]
you are referring to this dropdown correct?
![image](https://github.com/user-attachments/assets/2329ab46-2cf1-4eb4-9798-bc8071f76eb9)
I cannot repo this on windows in app or in browser. Can you tell me what platform you are using, and what type of input device?

**Comment by Amir-Rasteg** [comment]
closing since no further issue was given. If this is a problem, please give me details on the platform being used and how you are scrolling
