### ISSUE TITLE
Synapse and Neuron count sometimes do not show up

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#341]
Load essential genome. Despite health check having the neuron and synapse count, the values are not showing up.

Notes:
- Browser refresh does not fix the issue
- Changing cortical area size fixes the issue. After submitting the change the loading.. shows up and then the neuron and synapse count become visible

<img width="595" alt="image" src="https://github.com/user-attachments/assets/95e586de-6be2-4d24-a0fe-40a7eb3bbc83">

**Comment by Amir-Rasteg** [comment]
this has been resolved
