### ISSUE TITLE
Reload issue after new feature added on FEAGI

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#346]
It is no longer reload genome if any controller loads into FEAGI with corticals requirement where FEAGI will generate cortical automatically. 

New feature on FEAGI is when the controller, let's say pong, connected to FEAGI. FEAGI will see what the pong controller needs then load all corticals. It is already happening.

The problem is that BV doesn't detect nor reload genome once that happens.

Steps:
1) Load FEAGI and Bridge
2) Load BV
3) Load bare bones genome
4) Load webcam controller or any controller (without doing anything)

It should refresh itself, but it did not. The current workaround is to relaunch to see new corticals.

**Comment by Amir-Rasteg** [comment]
from my understanding this was an external issue and was resolved a while back. Please reopen this if that is not the case. In all likelyhood though, any further issue would simply be caused by no reset genome request being sent
