### ISSUE TITLE
Replace references to Afferent/Efferent to only Input / Output

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#349]
The use of terms Afferent and Efferent is only adding confusion and complexity. Simply keep Inputs as Afferent and Outputs to Efferents.

**Comment by Amir-Rasteg** [comment]
![image](https://github.com/user-attachments/assets/935ca71d-65e6-45db-ae5f-8446d4b422f0)
Spotted this, which has now been updated to Sensory and Motor

**Comment by Amir-Rasteg** [comment]
given that no further requests were made, closing the issue. Reopen the issue if anything is missed
