### ISSUE TITLE
copy feature issues

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#355]
If the name of a cortical area is already at the max text length, a copy of it will have its original name and FEAGI becomes stuck

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani working a fix for this on BV side but FEAGI should also be checking this input

**Comment by Amir-Rasteg** [comment]
https://github.com/feagi/feagi/issues/495

**Comment by Amir-Rasteg** [comment]
added a simple fix for the limiting the length of cortical area names when cloning.
However we need to add a more robust system BV wide for name length checks
