### ISSUE TITLE
wrong defintion for degeneracy constant

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#362]
as title

**Comment by Amir-Rasteg** [comment]
I am assuming you mean for the the tooltip of leftbar of the text "Degeneracy Constant"?

If not, please let me know.

Right now, the tooltip is "The number of bursts where the neuron cannot fire after consecutive fire count has been reached"

@m-nadji-tehrani what would you like this changed to?

**Comment by m-nadji-tehrani** [comment]
Here is the proper definition:
"The amount of PSP degradation after each neuron firing."

**Comment by Amir-Rasteg** [comment]
fixed
