### ISSUE TITLE
Crash when I load genome [LOCALLY]

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#364]
![Screenshot 2024-09-29 at 12 38 25 PM](https://github.com/user-attachments/assets/821f5378-3602-472e-8d18-a99265a6b45a)

steps:
1) Open BV before load genome
2) Load genome (any)
3) Error

**Comment by Amir-Rasteg** [comment]
I cannot repo this in accordance to your steps

**Comment by Amir-Rasteg** [comment]
This should have been fixed a while back
