### ISSUE TITLE
toggle MP PSP driven crash bV [LOCAL]

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#365]
![image](https://github.com/user-attachments/assets/a47766b1-6c36-40ef-b50a-9b3b7acd8f81)

**Comment by Kakcalu13** [comment]
Step:

1) select any cortical that has it on.
2) Turn it off. 
3) see it.

**Comment by Amir-Rasteg** [comment]
duplicate of https://github.com/feagi/brain-visualizer/issues/368
