### ISSUE TITLE
if you add a custom cortical more than 2 times, it crash BV

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#366]
Steps:
1) Add one custom cortical
2) Add another custom cortical
3) Add another custom cortical (see the error below)
![image](https://github.com/user-attachments/assets/a9873aec-6f06-4da1-bbf3-5beb333d2ac7)

**Comment by Amir-Rasteg** [comment]
I cannot repo this.

Looking at the error, I see it complaining about something in CB. Were you doing something there?

**Comment by Kakcalu13** [comment]
fixed
