### ISSUE TITLE
Custom disappears when click custom cortical area in CB

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#369]
https://github.com/user-attachments/assets/351c85d2-86fa-4f68-9479-b8048cd1dec6

**Comment by Amir-Rasteg** [comment]
I cant repo this.
I am guessing this has something to do with regions, but I need your genome you are using here to check

**Comment by Kakcalu13** [comment]
![image](https://github.com/user-attachments/assets/676d4b0b-46c9-49b8-87ca-bed31894e43d)

**Comment by Kakcalu13** [comment]
steps:

1) import a different gneome (any different genome) into this essential genome 
2) open cb/bm split
3) click edit on custom cortical area

**Comment by Amir-Rasteg** [comment]
> Confirmed, you need to import any genome to make this happen.
> 
> Each cortical will jump to region even if it doesn't have the cortical in first place

Check the logs of BV. I am 99% sure this is FEAGI sending inconsistent data

**Comment by Kakcalu13** [comment]
Sorry.


1) you load essential genome
2) Delete ALL vision
3) Download the genome
4) Load essential genome again
5) Import the genome you downloaded
6) Refresh (FEAGI needs to fix that part)
7) You open CB and click any vision region to edit

**Comment by Amir-Rasteg** [comment]
@m-nadji-tehrani I am betting the endpoint giving funni results is "/v1/region/regions_members"

**Comment by m-nadji-tehrani** [comment]
Fixed in a local branch and will be pushed to public repo shortly
