### ISSUE TITLE
BV freezes in HTML but crash in local

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#383]
![image](https://github.com/user-attachments/assets/87e293a8-3c96-4771-8386-dd96fa229bcc)

This is not something I can repo. It just randomly occur.

Second time:
![image](https://github.com/user-attachments/assets/3bb547c5-689b-4e08-94bb-a447da931ef0)

it happened when I load controller and it crashed.

I load another genome during runtime. See here:
![image](https://github.com/user-attachments/assets/eb2d15e0-0dc4-47f0-b2b7-e5dcc68b892d)

All related to CB position issue

**Comment by m-nadji-tehrani** [comment]
here is another data point:
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/cccbc385-d824-4e46-9fcd-85fc98465898">

**Comment by Amir-Rasteg** [comment]
These are 2 separate crashes looking at the logs

**Comment by Amir-Rasteg** [comment]
this issue was resolved in a separate issue a while back, closing for now
