### ISSUE TITLE
Exception while deleting a cortical mapping

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#384]
Had cortical mapping between two cortical areas. Clicked on the cortical area properties on the source and from the connection dropdown found the desirable mapping which was the only one. Clicked on the trash can and selected "yes" to confirm the deletion. Exception occurred

<img width="1562" alt="image" src="https://github.com/user-attachments/assets/221f7f51-68e2-448b-b407-966624775520">

**Comment by Amir-Rasteg** [comment]
This issue was resolved a while ago, closing for now
