### ISSUE TITLE
Exception when deleting an Afferent mapping from the "Cortical Area Details" panel

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#385]
Repo steps:
- have a cortical area that has many different afferent connections
- on 3D monitor, click on the cortical area then click pencil
- open the connections and start deleting the afferent connections one by one from the list by clicking on the trashcan icon
- after confirming the deletion, move on and delete another afferent mapping

Notes: 
- FEAGI logs did not show any exception but it seems like the api call to delete the mapping was properly received made when failure occurred

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/a6487e6b-942d-4740-8452-81fc2d547025">

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/3f426689-00fe-4695-90a5-db16bcbb1743">

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/0332ad9d-7b7b-4813-82d8-eef93f80479a">

**Comment by m-nadji-tehrani** [comment]
Here is the genome I can reliably repo the issue. Use the cortical area called front and start deleting the affarents
[response_1730731498395.json](https://github.com/user-attachments/files/17620293/response_1730731498395.json)

**Comment by Amir-Rasteg** [comment]
addressed with a work around. We need to find the root cause of these invalid nodes
