### ISSUE TITLE
pop-up tooltip is not showing up inside a brain region

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#391]
1.  Open a brain region with multiple cortical areas within. 
2. Click on the cortical area.
3. Pop up menu should show up but it doesn't.
4. Alternatively, select multiple cortical area by dragging the mouse over and pop-up is not showing for it either.

**Comment by Amir-Rasteg** [comment]
further more drag select just broke too

**Comment by Amir-Rasteg** [comment]
addressed in latest PR
