### ISSUE TITLE
Cortical area names being cut off on 3D monitor

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#392]
Cortical area names are being cut off. increase the allowable width and enable text wrapping for very long names. Account for a min of 30 chars. If name is longer that UI can fit, have ... at the end but ensure the beginning is fully visible and no part of cut off

<img width="542" alt="image" src="https://github.com/user-attachments/assets/b6923d66-d7c7-4e7e-8ab3-7165ef183aee">

**Comment by Amir-Rasteg** [comment]
addressed in latest PR
