### ISSUE TITLE
Label support for servo position opu issue

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#394]
Currently, It doesn't work well with mujoco when it comes to servo position opu.

When I ran Petoi, it's able to display the servo position label. It doesn't work for mujoco.

Steps:
1) git clone git@github.com:feagi/controllers.git -b head_gyro
2) cd controllers/simulators/mujoco
3) pip3 install -r requirements.txt
4) python3 controller.py

drag ur mouse on the servo position opu and see no label

**Comment by Amir-Rasteg** [comment]
addressed in latest PR
