### ISSUE TITLE
Edit icons on Quick Connect selections are not showing up

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#40]
Far right side of the quick connect is supposed to have an edit icon for user to change selections which is missing on latest build dated 2023-11-07T15:15:30

<img width="482" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/cc19ffe2-a21f-4f09-b631-9adcf0c7fe15">

**Comment by Amir-Rasteg** [comment]
Resolved a while ago
