### ISSUE TITLE
Exception when hovering mouse on input/output cortical areas

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#403]
Have an agent connected with FEAGI that has device labels. When hovering mouse on top of the output cortical areas the attached exception occur. 

Note: Staging does not have this problem but the global selection system local branch does.

<img width="1359" alt="image" src="https://github.com/user-attachments/assets/e68872e1-bca3-4430-8b6d-a6d74e4db1e7">

**Comment by Amir-Rasteg** [comment]
addressed in latest PR
