### ISSUE TITLE
Vision tuning panel issues

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#418]
- Some labels are shown as "label" as shown below
<img width="271" alt="image" src="https://github.com/user-attachments/assets/53d8e89f-fbc5-40a8-937a-b27c6878dd48" />

- cortical properties does not open and leads to a crash
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/5c393ab9-d93a-41ff-8fbd-661f477cee92" />

**Comment by Amir-Rasteg** [comment]
this has been resolved a in the latest branch
