### ISSUE TITLE
Add ability to duplicate a cortical area

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#50]
Need ability to duplicate a cortical area by allowing user to select a source cortical area and click on a duplicate button. 

In this process:
- All neuronal properties will match source
- Cortical dimensions will match source
- User will select a new name and new position
- No mapping will be duplicated

**Comment by Amir-Rasteg** [comment]
Feature complete BV side in branch "CORE-clone"
Awaiting completion on feagi side....

**Comment by Amir-Rasteg** [comment]
Feature confirmed added
