### ISSUE TITLE
Add multi edit capability to Brain Visualizer

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#53]
It happens often that the same property needs to be updated on multiple cortical areas at the same time. As an example to turn on PSP Uniformity, set the same Z value, etc. 

Develop the feature so user can select multiple cortical areas at the same time and use the cortical properties panel in a controlled way to set one or multiple property and save it against all selected cortical areas at the same time.

This feature needs to be available for both BV and CB.

**Comment by Amir-Rasteg** [comment]
complete
