### ISSUE TITLE
Creating a cortical area in circuit builder is asking for 3D coordinates

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#54]
Cortical area creation should be context sensitive so when user is in CB to ask for 2D coordinates and when in BV to ask for 3D coordinates instead.

**Comment by Amir-Rasteg** [comment]
Given split screen view, this should be revisted

**Comment by Amir-Rasteg** [comment]
we should instead elect for a gizmo or another system to move 3d volumes easily, and keep the numerical fields should the user optionally feel like being precise
