### ISSUE TITLE
Add split mode to Brain Visualizer

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#55]
When designing a genome, there are many situations where you like to observe the live brain activities while analyzing the brain circuitry. Having a Split View would eliminate the need to switch back and forth and helps with a better design experience.

1. Need ability to turn on split mode and give user ability to adjust the horizontal split point so different size can be allocated to Circuit Builder and 3D Visualizer

**Comment by Amir-Rasteg** [comment]
BASIC split screen mode has been add. However we are looking to a better system with independent panel rendering allowing multiple instances of CB and BM. Requires some decent refactoring

**Comment by Amir-Rasteg** [comment]
Basic split screen has been added
