### ISSUE TITLE
Quick Connect to use Projector by default

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#56]
To promote simplicity and ease of use, pre-select Projector morphology by default so when user selects source then destination the UI be ready to finalize the connection. User will have the option to edit the morphology and choose another morphology.

Projector morphology is the simplest and most used morphology hence such move can satisfy more than %80 of situations.

**Comment by Amir-Rasteg** [comment]
This has been resolved for a while
