### ISSUE TITLE
Mouse pointer and cortical area location become separated when dragging on Circuit Builder

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#59]
When dragging a cortical area in circuit builder in HTML exported version, the final position of the mouse and the initial contact point with the cortical area become further apart when further dragged out.

**Comment by Amir-Rasteg** [comment]
This issue seems to be caused by zoom settings in the browser (but this can vary per browser).

**Comment by Amir-Rasteg** [comment]
this issue is resolved
