### ISSUE TITLE
Outdated Tutorial

### ISSUE THREAD

**Issue by vanessaneuraville** [feagi/brain-visualizer#70]
- Icons aren't in the same location
- Missing a step 6
- Needs more descriptions (ex. input = sensory, output = motor, interconnect = custom)

**Comment by vanessaneuraville** [comment]
Suggestion: ability to click on the entire line to open the mappings box, instead of just clicking on the small box

**Comment by m-nadji-tehrani** [comment]
Tutorials have been removed from brain visualizer and moved to FEAGI playground
