### ISSUE TITLE
FEAGI network endpoint needs to be updated 

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#77]
On FEAGI side, /v1/feagi/feagi/network has changed to /v1/network/network

<img width="1571" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/ecf5a514-cca2-4067-9055-943ebb5c8902">

**Comment by Amir-Rasteg** [comment]
This endpoint seems to never be used by BV? I dont see a reference to it in the [addresslist.gd](https://github.com/feagi/brain-visualizer/blob/staging/godot_source/Feagi-Godot-Interface/Core/Networking/AddressList.gd)

**Comment by Amir-Rasteg** [comment]
closed, not relevant to BV
