### ISSUE TITLE
Cortical Area selection improvements across 3D monitor and Circuit Builder

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#78]
in CB, currently when user clicks on a cortical area, the color of the titlebar associated with the cortical area changes as an indication of it being selected. 

Extend this feature to 3D monitor so when user selects a cortical in 3D monitor, then the associated cortical area in CB to be highlighted as well? This is primarily for split-view usability.

**Comment by Amir-Rasteg** [comment]
technically, cortical areas in 3DM are not "selected", theres only mouse over animations and just the event that fires when being clicked, that opening a window. We need to discuss this futher
