### ISSUE TITLE
Adjust the default location during cortical area creation

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#80]
Current cortical area 3D position default is 0,0,0 which falls under the red 3D axis indicator. User has to always remember to change the location and the green location indicator is at first invisible due to such overlap.

Set the default position to 40, 0 , 0 instead

<img width="422" alt="image" src="https://github.com/feagi/brain-visualizer/assets/26581495/30716aff-731c-4de9-950a-7dae3989c285">

**Comment by Amir-Rasteg** [comment]
resolved
